# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db798a111fbd44e969ac6ae93f7fbe347f21f6498ebe25018b35d5f5e2255fa1e0b4d3366c3cecd181bb4207d4e0aed782d7faee9974b642870da02b77420d91

test:
  secret_key_base: 9e1e0ab9ba1f0b5b0da20831f10f35bc06475852e7181a680e603d281719c8274d7284d67eb8576716694661b282dce2bc50c9bba1a9e3cedb52285760d1c48f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
